[project]
name = "homeassistant.sensor.feedparser"
version = "1.3.0"
description = "Home Assistant custom integration to parse RSS feeds"
maintainers = [
  { name = "Tim Bayer", email = "mail@timbayer.de" }
]
keywords = [
  "homeassistant",
  "rss",
  "feedparser",
  "feed",
  "parser",
  "custom-component",
  "custom-integration"
]
classifiers = [
  "Intended Audience :: End Users/Desktop",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14"
]
requires-python = ">=3.13.2"
dependencies = [
  "feedparser==6.0.12",
  "homeassistant",
  "python-dateutil==2.9.0.post0"
]

[project.optional-dependencies]
dev = [
  "black",
  "homeassistant-stubs",
  "pytest==9.1.1",
  "mypy",
  "ruff",
  "types-python-dateutil",
  "types-PyYAML",
  "types-requests",
  "voluptuous-stubs",
  "pyyaml",
  "bumpver"
]

[project.urls]
"Source Code" = "https://github.com/timmaurice/feedparser"
"Bug Reports" = "https://github.com/timmaurice/feedparser/issues"

[tool.setuptools]
py-modules = ["custom_components.feedparser"]

[tool.black]
line-length = 88
# skip-string-normalization = true
target-version = ["py311"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[[tool.mypy.overrides]]
module = "feedparser.*"
# Workaround till https://github.com/kurtmckee/feedparser/pull/282 gets merged to the main branch
disable_error_code = ["attr-defined", "import"]

[tool.pytest.ini_options]
pythonpath = [".", "tests"]
filterwarnings = [
  "ignore:Inheritance class HomeAssistantApplication from web.Application is discouraged:DeprecationWarning"
]

[tool.bumpver]
current_version = "1.3.0"
version_pattern = "MAJOR.MINOR.PATCH[PYTAGNUM]"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"', 'version = "{version}"']
"custom_components/feedparser/manifest.json" = ['version": "{version}"']
"custom_components/feedparser/sensor.py" = ['__version__ = "{version}"']
